from cayley_permutations import CayleyPermutation
from gridded_cayley_permutations import GriddedCayleyPerm, Tiling
from tilescope.strategies.row_column_separation import LessThanOrEqualRowColSeparation
from itertools import combinations


def test_ltoreq_rc_sep():
    """One row separates in 3 columns, make sure can still have
    gcps going across the whole row."""
    tiling = Tiling(
        (
            GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 0),)),
            GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 0),)),
            GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 0), (0, 0))),
            GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 1), (1, 1))),
            GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 1), (2, 1))),
            GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 1), (1, 1))),
            GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 1), (2, 1))),
            GriddedCayleyPerm(CayleyPermutation((0, 1)), ((2, 1), (2, 1))),
            GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 0), (0, 0))),
            GriddedCayleyPerm(CayleyPermutation((0, 1, 2)), ((0, 0), (0, 1), (0, 1))),
            GriddedCayleyPerm(CayleyPermutation((0, 1, 2)), ((0, 1), (0, 1), (0, 1))),
            GriddedCayleyPerm(CayleyPermutation((1, 0, 2)), ((0, 1), (0, 0), (0, 1))),
            GriddedCayleyPerm(
                CayleyPermutation((1, 0, 2, 0)), ((0, 1), (0, 1), (0, 1), (0, 1))
            ),
            GriddedCayleyPerm(
                CayleyPermutation((1, 0, 2, 0)), ((0, 1), (0, 1), (0, 1), (1, 1))
            ),
            GriddedCayleyPerm(
                CayleyPermutation((1, 0, 2, 0)), ((0, 1), (0, 1), (0, 1), (2, 1))
            ),
        ),
        (),
        (3, 2),
    )

    out = {
        Tiling(
            (
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 3),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 3),)),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 0), (0, 0))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 2), (0, 2))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 2), (1, 2))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 2), (2, 2))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 1), (1, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 1), (1, 2))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 1), (2, 2))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 2), (1, 2))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 2), (2, 2))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((2, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((2, 1), (2, 2))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((2, 2), (2, 2))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 0), (0, 0))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 2), (0, 2))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 2), (1, 2))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 2), (2, 2))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 2), (1, 2))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 2), (2, 2))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((2, 2), (2, 2))),
                GriddedCayleyPerm(
                    CayleyPermutation((0, 1, 2)), ((0, 0), (0, 2), (0, 3))
                ),
                GriddedCayleyPerm(
                    CayleyPermutation((0, 1, 2)), ((0, 0), (0, 3), (0, 3))
                ),
                GriddedCayleyPerm(
                    CayleyPermutation((0, 1, 2)), ((0, 2), (0, 3), (0, 3))
                ),
                GriddedCayleyPerm(
                    CayleyPermutation((0, 1, 2)), ((0, 3), (0, 3), (0, 3))
                ),
                GriddedCayleyPerm(
                    CayleyPermutation((1, 0, 2)), ((0, 2), (0, 0), (0, 3))
                ),
                GriddedCayleyPerm(
                    CayleyPermutation((1, 0, 2)), ((0, 3), (0, 0), (0, 3))
                ),
                GriddedCayleyPerm(
                    CayleyPermutation((1, 0, 2, 0)), ((0, 3), (0, 2), (0, 3), (0, 2))
                ),
                GriddedCayleyPerm(
                    CayleyPermutation((1, 0, 2, 0)), ((0, 3), (0, 2), (0, 3), (1, 2))
                ),
                GriddedCayleyPerm(
                    CayleyPermutation((1, 0, 2, 0)), ((0, 3), (0, 2), (0, 3), (2, 2))
                ),
                GriddedCayleyPerm(
                    CayleyPermutation((1, 0, 2, 0)), ((0, 3), (0, 3), (0, 3), (0, 3))
                ),
            ),
            (
                (GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 2),)),),
                (
                    GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 2),)),
                    GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 2),)),
                ),
            ),
            (3, 4),
        ),
        Tiling(
            (
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 3),)),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 0), (0, 0))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 2), (0, 2))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 2), (1, 2))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 2), (1, 3))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 2), (2, 2))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 3), (1, 3))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 2), (1, 2))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 2), (1, 3))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 2), (2, 2))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 3), (1, 3))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((2, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((2, 1), (2, 2))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((2, 2), (2, 2))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 0), (0, 0))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 2), (0, 2))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 2), (1, 2))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 2), (2, 2))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 2), (1, 2))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 2), (2, 2))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((2, 2), (2, 2))),
                GriddedCayleyPerm(
                    CayleyPermutation((0, 1, 2)), ((0, 0), (0, 2), (0, 3))
                ),
                GriddedCayleyPerm(
                    CayleyPermutation((0, 1, 2)), ((0, 0), (0, 3), (0, 3))
                ),
                GriddedCayleyPerm(
                    CayleyPermutation((0, 1, 2)), ((0, 2), (0, 3), (0, 3))
                ),
                GriddedCayleyPerm(
                    CayleyPermutation((0, 1, 2)), ((0, 3), (0, 3), (0, 3))
                ),
                GriddedCayleyPerm(
                    CayleyPermutation((1, 0, 2)), ((0, 2), (0, 0), (0, 3))
                ),
                GriddedCayleyPerm(
                    CayleyPermutation((1, 0, 2)), ((0, 3), (0, 0), (0, 3))
                ),
                GriddedCayleyPerm(
                    CayleyPermutation((1, 0, 2)), ((0, 3), (0, 2), (0, 3))
                ),
                GriddedCayleyPerm(
                    CayleyPermutation((1, 0, 2, 0)), ((0, 3), (0, 3), (0, 3), (0, 3))
                ),
                GriddedCayleyPerm(
                    CayleyPermutation((1, 0, 2, 0)), ((0, 3), (0, 3), (0, 3), (1, 3))
                ),
            ),
            (
                (
                    GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 2),)),
                    GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 2),)),
                ),
                (GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 2),)),),
            ),
            (3, 4),
        ),
        Tiling(
            (
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 3),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 3),)),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 0), (0, 0))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 1), (1, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((2, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 0), (0, 0))),
                GriddedCayleyPerm(
                    CayleyPermutation((0, 1, 2)), ((0, 0), (0, 3), (0, 3))
                ),
                GriddedCayleyPerm(
                    CayleyPermutation((0, 1, 2)), ((0, 3), (0, 3), (0, 3))
                ),
                GriddedCayleyPerm(
                    CayleyPermutation((1, 0, 2)), ((0, 3), (0, 0), (0, 3))
                ),
                GriddedCayleyPerm(
                    CayleyPermutation((1, 0, 2, 0)), ((0, 3), (0, 3), (0, 3), (0, 3))
                ),
            ),
            (),
            (3, 4),
        ),
        Tiling(
            (
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 3),)),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 0), (0, 0))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 3), (1, 3))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 3), (1, 3))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((2, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 0), (0, 0))),
                GriddedCayleyPerm(
                    CayleyPermutation((0, 1, 2)), ((0, 0), (0, 3), (0, 3))
                ),
                GriddedCayleyPerm(
                    CayleyPermutation((0, 1, 2)), ((0, 3), (0, 3), (0, 3))
                ),
                GriddedCayleyPerm(
                    CayleyPermutation((1, 0, 2)), ((0, 3), (0, 0), (0, 3))
                ),
                GriddedCayleyPerm(
                    CayleyPermutation((1, 0, 2, 0)), ((0, 3), (0, 3), (0, 3), (0, 3))
                ),
                GriddedCayleyPerm(
                    CayleyPermutation((1, 0, 2, 0)), ((0, 3), (0, 3), (0, 3), (1, 3))
                ),
            ),
            (),
            (3, 4),
        ),
    }

    assert set(LessThanOrEqualRowColSeparation(tiling).row_col_separation()) == out


def test_ltoreq_5_cols():
    """5x1 tiling with less than or equal row separation."""
    obs = []
    cells = [(0, 0), (1, 0), (2, 0), (3, 0), (4, 0)]
    for cell1, cell2 in combinations(cells, 2):
        obs.append(GriddedCayleyPerm(CayleyPermutation([0, 1]), [cell1, cell2]))

    tiling = Tiling(
        obs,
        (),
        (5, 1),
    )

    out = {
        Tiling(
            (
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((3, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((4, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 1), (0, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 1), (1, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 1), (1, 2))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 1), (2, 2))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 1), (3, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 1), (4, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 2), (1, 2))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 2), (2, 2))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 1), (1, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 1), (2, 2))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 1), (3, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 1), (4, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 2), (2, 2))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((2, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((2, 1), (3, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((2, 1), (4, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((3, 0), (4, 0))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((3, 0), (4, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((3, 1), (3, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((3, 1), (4, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((4, 1), (4, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 1), (0, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 1), (1, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 1), (3, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 1), (4, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 1), (1, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 1), (3, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 1), (4, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((2, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((2, 1), (3, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((2, 1), (4, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((3, 1), (3, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((3, 1), (4, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((4, 1), (4, 1))),
            ),
            (
                (
                    GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 1),)),
                    GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 1),)),
                    GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 1),)),
                ),
                (
                    GriddedCayleyPerm(CayleyPermutation((0,)), ((3, 1),)),
                    GriddedCayleyPerm(CayleyPermutation((0,)), ((4, 1),)),
                ),
            ),
            (5, 3),
        ),
        Tiling(
            (
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((3, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((3, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((4, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((4, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 2), (1, 2))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 2), (2, 2))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 2), (2, 2))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((3, 0), (4, 0))),
            ),
            (),
            (5, 3),
        ),
        Tiling(
            (
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((3, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((3, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((4, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((4, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 0), (2, 0))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 0), (3, 0))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 0), (4, 0))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((2, 0), (3, 0))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((2, 0), (4, 0))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((3, 0), (4, 0))),
            ),
            (),
            (5, 3),
        ),
        Tiling(
            (
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((3, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((4, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 1), (0, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 1), (1, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 1), (1, 2))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 1), (3, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 1), (4, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 2), (1, 2))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 1), (1, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 1), (3, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 1), (4, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((2, 0), (3, 0))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((2, 0), (3, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((2, 0), (4, 0))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((2, 0), (4, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((2, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((2, 1), (3, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((2, 1), (4, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((3, 0), (4, 0))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((3, 0), (4, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((3, 1), (3, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((3, 1), (4, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((4, 1), (4, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 1), (0, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 1), (1, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 1), (3, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 1), (4, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 1), (1, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 1), (3, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 1), (4, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((2, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((2, 1), (3, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((2, 1), (4, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((3, 1), (3, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((3, 1), (4, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((4, 1), (4, 1))),
            ),
            (
                (
                    GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 1),)),
                    GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 1),)),
                ),
                (
                    GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 1),)),
                    GriddedCayleyPerm(CayleyPermutation((0,)), ((3, 1),)),
                    GriddedCayleyPerm(CayleyPermutation((0,)), ((4, 1),)),
                ),
            ),
            (5, 3),
        ),
        Tiling(
            (
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((3, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((4, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 1), (0, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 1), (1, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 1), (3, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 1), (4, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 0), (2, 0))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 0), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 0), (3, 0))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 0), (3, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 0), (4, 0))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 0), (4, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 1), (1, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 1), (3, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 1), (4, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((2, 0), (3, 0))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((2, 0), (3, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((2, 0), (4, 0))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((2, 0), (4, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((2, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((2, 1), (3, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((2, 1), (4, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((3, 0), (4, 0))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((3, 0), (4, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((3, 1), (3, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((3, 1), (4, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((4, 1), (4, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 1), (0, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 1), (1, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 1), (3, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 1), (4, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 1), (1, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 1), (3, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 1), (4, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((2, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((2, 1), (3, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((2, 1), (4, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((3, 1), (3, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((3, 1), (4, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((4, 1), (4, 1))),
            ),
            (
                (GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 1),)),),
                (
                    GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 1),)),
                    GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 1),)),
                    GriddedCayleyPerm(CayleyPermutation((0,)), ((3, 1),)),
                    GriddedCayleyPerm(CayleyPermutation((0,)), ((4, 1),)),
                ),
            ),
            (5, 3),
        ),
        Tiling(
            (
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((3, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((4, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 1), (0, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 1), (1, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 1), (1, 2))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 1), (2, 2))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 1), (3, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 1), (3, 2))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 1), (4, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 2), (1, 2))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 2), (2, 2))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 2), (3, 2))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 1), (1, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 1), (2, 2))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 1), (3, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 1), (3, 2))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 1), (4, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 2), (2, 2))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 2), (3, 2))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((2, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((2, 1), (3, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((2, 1), (3, 2))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((2, 1), (4, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((2, 2), (3, 2))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((3, 1), (3, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((3, 1), (4, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((4, 1), (4, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 1), (0, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 1), (1, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 1), (3, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 1), (4, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 1), (1, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 1), (3, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 1), (4, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((2, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((2, 1), (3, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((2, 1), (4, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((3, 1), (3, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((3, 1), (4, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((4, 1), (4, 1))),
            ),
            (
                (
                    GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 1),)),
                    GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 1),)),
                    GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 1),)),
                    GriddedCayleyPerm(CayleyPermutation((0,)), ((3, 1),)),
                ),
                (GriddedCayleyPerm(CayleyPermutation((0,)), ((4, 1),)),),
            ),
            (5, 3),
        ),
        Tiling(
            (
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((3, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((3, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((4, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((4, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 2), (1, 2))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((2, 0), (3, 0))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((2, 0), (4, 0))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((3, 0), (4, 0))),
            ),
            (),
            (5, 3),
        ),
        Tiling(
            (
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((3, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((3, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((4, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((4, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 2), (1, 2))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 2), (2, 2))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 2), (3, 2))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 2), (2, 2))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 2), (3, 2))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((2, 2), (3, 2))),
            ),
            (),
            (5, 3),
        ),
    }

    assert set(LessThanOrEqualRowColSeparation(tiling).row_col_separation()) == out


def test_ltoreq_rc_sep_multiple_rows():
    """Three rows of the tiling can separate."""
    tiling = Tiling(
        (
            GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 0),)),
            GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 2),)),
            GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 0), (2, 0))),
            GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 1), (1, 1))),
            GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 1), (2, 1))),
            GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 1), (1, 1))),
            GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 1), (2, 1))),
            GriddedCayleyPerm(CayleyPermutation((1, 0)), ((2, 1), (2, 1))),
            GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 2), (1, 2))),
        ),
        (),
        (3, 3),
    )

    out = {
        Tiling(
            (
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 5),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 6),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 7),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 5),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 7),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 8),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 3),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 6),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 7),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 8),)),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 1), (0, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 4), (0, 4))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 4), (1, 4))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 4), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 4), (1, 4))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 4), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((2, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((2, 4), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 1), (0, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 3), (1, 3))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 4), (0, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 4), (1, 3))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 4), (1, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 4), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 3), (1, 3))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 4), (1, 3))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 4), (1, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 4), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((2, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((2, 4), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((2, 5), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((2, 5), (2, 5))),
            ),
            (
                (GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 1),)),),
                (
                    GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 4),)),
                    GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 4),)),
                ),
                (GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 1),)),),
                (GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 4),)),),
            ),
            (3, 9),
        ),
        Tiling(
            (
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 4),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 5),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 6),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 7),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 3),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 4),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 7),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 8),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 3),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 4),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 6),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 7),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 8),)),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 5), (1, 5))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 5), (2, 5))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((2, 5), (2, 5))),
            ),
            (),
            (3, 9),
        ),
        Tiling(
            (
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 4),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 5),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 6),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 4),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 5),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 8),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 3),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 4),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 6),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 7),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 8),)),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 7), (0, 7))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 7), (1, 7))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 7), (1, 7))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 3), (1, 3))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 7), (0, 7))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 7), (1, 7))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 3), (1, 3))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 7), (1, 7))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((2, 5), (2, 5))),
            ),
            (
                (GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 7),)),),
                (GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 7),)),),
            ),
            (3, 9),
        ),
        Tiling(
            (
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 5),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 6),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 5),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 8),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 3),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 6),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 7),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 8),)),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 1), (0, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 4), (0, 4))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 4), (1, 4))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 4), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 7), (0, 7))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 7), (1, 7))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 4), (1, 4))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 4), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 7), (1, 7))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((2, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((2, 4), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 1), (0, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 3), (1, 3))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 4), (0, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 4), (1, 3))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 4), (1, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 4), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 7), (0, 7))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 7), (1, 7))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 3), (1, 3))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 4), (1, 3))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 4), (1, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 4), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 7), (1, 7))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((2, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((2, 4), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((2, 5), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((2, 5), (2, 5))),
            ),
            (
                (GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 1),)),),
                (
                    GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 4),)),
                    GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 4),)),
                ),
                (GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 7),)),),
                (GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 7),)),),
                (GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 1),)),),
                (GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 4),)),),
            ),
            (3, 9),
        ),
        Tiling(
            (
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 4),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 5),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 6),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 7),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 4),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 5),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 7),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 8),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 3),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 4),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 6),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 7),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 8),)),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 1), (0, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((2, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 1), (0, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 3), (1, 3))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 3), (1, 3))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((2, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((2, 5), (2, 5))),
            ),
            (
                (GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 1),)),),
                (GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 1),)),),
            ),
            (3, 9),
        ),
        Tiling(
            (
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 4),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 5),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 6),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 3),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 4),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 8),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 3),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 4),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 6),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 7),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 8),)),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 7), (0, 7))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 7), (1, 7))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 7), (1, 7))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 7), (0, 7))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 7), (1, 7))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 5), (1, 5))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 5), (2, 5))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 7), (1, 7))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((2, 5), (2, 5))),
            ),
            (
                (GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 7),)),),
                (GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 7),)),),
            ),
            (3, 9),
        ),
        Tiling(
            (
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 5),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 6),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 5),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 8),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 3),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 6),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 7),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 8),)),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 4), (0, 4))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 4), (1, 4))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 4), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 7), (0, 7))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 7), (1, 7))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 4), (1, 4))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 4), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 7), (1, 7))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((2, 4), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 3), (1, 3))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 4), (0, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 4), (1, 3))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 4), (1, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 4), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 7), (0, 7))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 7), (1, 7))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 3), (1, 3))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 4), (1, 3))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 4), (1, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 4), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 7), (1, 7))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((2, 4), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((2, 5), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((2, 5), (2, 5))),
            ),
            (
                (
                    GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 4),)),
                    GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 4),)),
                ),
                (GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 7),)),),
                (GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 7),)),),
                (GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 4),)),),
            ),
            (3, 9),
        ),
        Tiling(
            (
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 4),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 5),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 6),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 7),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 3),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 4),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 7),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 8),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 3),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 4),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 6),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 7),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 8),)),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 1), (0, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((2, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 1), (0, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 5), (1, 5))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 5), (2, 5))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((2, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((2, 5), (2, 5))),
            ),
            (
                (GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 1),)),),
                (GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 1),)),),
            ),
            (3, 9),
        ),
        Tiling(
            (
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 4),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 5),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 6),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 3),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 4),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 8),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 3),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 4),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 6),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 7),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 8),)),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 1), (0, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 7), (0, 7))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 7), (1, 7))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 7), (1, 7))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((2, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 1), (0, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 7), (0, 7))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 7), (1, 7))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 5), (1, 5))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 5), (2, 5))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 7), (1, 7))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((2, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((2, 5), (2, 5))),
            ),
            (
                (GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 1),)),),
                (GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 7),)),),
                (GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 7),)),),
                (GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 1),)),),
            ),
            (3, 9),
        ),
        Tiling(
            (
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 5),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 6),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 7),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 3),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 7),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 8),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 3),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 6),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 7),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 8),)),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 4), (0, 4))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 4), (1, 4))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 4), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 4), (1, 4))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 4), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((2, 4), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 4), (0, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 4), (1, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 4), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 4), (1, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 4), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 5), (1, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 5), (1, 5))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 5), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 5), (2, 5))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((2, 4), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((2, 5), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((2, 5), (2, 5))),
            ),
            (
                (GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 4),)),),
                (
                    GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 4),)),
                    GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 4),)),
                ),
            ),
            (3, 9),
        ),
        Tiling(
            (
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 5),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 6),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 3),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 8),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 3),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 6),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 7),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 8),)),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 4), (0, 4))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 4), (1, 4))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 4), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 7), (0, 7))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 7), (1, 7))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 4), (1, 4))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 4), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 7), (1, 7))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((2, 4), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 4), (0, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 4), (1, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 4), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 7), (0, 7))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 7), (1, 7))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 4), (1, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 4), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 5), (1, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 5), (1, 5))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 5), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 5), (2, 5))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 7), (1, 7))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((2, 4), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((2, 5), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((2, 5), (2, 5))),
            ),
            (
                (GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 4),)),),
                (GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 7),)),),
                (
                    GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 4),)),
                    GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 4),)),
                ),
                (GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 7),)),),
            ),
            (3, 9),
        ),
        Tiling(
            (
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 4),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 5),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 6),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 4),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 5),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 8),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 3),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 4),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 6),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 7),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 8),)),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 1), (0, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 7), (0, 7))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 7), (1, 7))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 7), (1, 7))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((2, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 1), (0, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 3), (1, 3))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 7), (0, 7))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 7), (1, 7))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 3), (1, 3))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 7), (1, 7))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((2, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((2, 5), (2, 5))),
            ),
            (
                (GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 1),)),),
                (GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 7),)),),
                (GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 7),)),),
                (GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 1),)),),
            ),
            (3, 9),
        ),
        Tiling(
            (
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 5),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 6),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 7),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 5),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 7),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 8),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 3),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 6),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 7),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 8),)),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 4), (0, 4))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 4), (1, 4))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 4), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 4), (1, 4))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 4), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((2, 4), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 3), (1, 3))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 4), (0, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 4), (1, 3))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 4), (1, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 4), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 3), (1, 3))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 4), (1, 3))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 4), (1, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 4), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((2, 4), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((2, 5), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((2, 5), (2, 5))),
            ),
            (
                (
                    GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 4),)),
                    GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 4),)),
                ),
                (GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 4),)),),
            ),
            (3, 9),
        ),
        Tiling(
            (
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 5),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 6),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 7),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 3),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 7),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 8),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 3),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 6),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 7),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 8),)),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 1), (0, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 4), (0, 4))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 4), (1, 4))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 4), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 4), (1, 4))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 4), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((2, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((2, 4), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 1), (0, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 4), (0, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 4), (1, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 4), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 4), (1, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 4), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 5), (1, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 5), (1, 5))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 5), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 5), (2, 5))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((2, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((2, 4), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((2, 5), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((2, 5), (2, 5))),
            ),
            (
                (GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 1),)),),
                (GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 4),)),),
                (
                    GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 4),)),
                    GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 4),)),
                ),
                (GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 1),)),),
            ),
            (3, 9),
        ),
        Tiling(
            (
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 5),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 6),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 3),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 8),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 3),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 6),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 7),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 8),)),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 1), (0, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 4), (0, 4))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 4), (1, 4))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 4), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 7), (0, 7))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((0, 7), (1, 7))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 4), (1, 4))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 4), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((1, 7), (1, 7))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((2, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((0, 1)), ((2, 4), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 1), (0, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 4), (0, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 4), (1, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 4), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 7), (0, 7))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 7), (1, 7))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 4), (1, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 4), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 5), (1, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 5), (1, 5))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 5), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 5), (2, 5))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 7), (1, 7))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((2, 1), (2, 1))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((2, 4), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((2, 5), (2, 4))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((2, 5), (2, 5))),
            ),
            (
                (GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 1),)),),
                (GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 4),)),),
                (GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 7),)),),
                (
                    GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 4),)),
                    GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 4),)),
                ),
                (GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 7),)),),
                (GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 1),)),),
            ),
            (3, 9),
        ),
        Tiling(
            (
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 4),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 5),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 6),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((0, 7),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 0),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 4),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 5),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 7),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((1, 8),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 1),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 2),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 3),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 4),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 6),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 7),)),
                GriddedCayleyPerm(CayleyPermutation((0,)), ((2, 8),)),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((0, 3), (1, 3))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((1, 3), (1, 3))),
                GriddedCayleyPerm(CayleyPermutation((1, 0)), ((2, 5), (2, 5))),
            ),
            (),
            (3, 9),
        ),
    }

    assert set(LessThanOrEqualRowColSeparation(tiling).row_col_separation()) == out
